/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_linjian_sd_daemon_java_NativeUtil */

#ifndef _Included_org_linjian_sd_daemon_java_NativeUtil
#define _Included_org_linjian_sd_daemon_java_NativeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_linjian_sd_daemon_java_NativeUtil
 * Method:    sd_listen_fds
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_linjian_sd_1daemon_1java_NativeUtil_sd_1listen_1fds
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_linjian_sd_daemon_java_NativeUtil
 * Method:    sd_booted
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_linjian_sd_1daemon_1java_NativeUtil_sd_1booted
  (JNIEnv *, jclass);

/*
 * Class:     org_linjian_sd_daemon_java_NativeUtil
 * Method:    getpid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_linjian_sd_1daemon_1java_NativeUtil_getpid
  (JNIEnv *, jclass);

/*
 * Class:     org_linjian_sd_daemon_java_NativeUtil
 * Method:    getenv
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_linjian_sd_1daemon_1java_NativeUtil_getenv
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_linjian_sd_daemon_java_NativeUtil
 * Method:    setenv
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_linjian_sd_1daemon_1java_NativeUtil_setenv
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     org_linjian_sd_daemon_java_NativeUtil
 * Method:    system
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_linjian_sd_1daemon_1java_NativeUtil_system
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
